import type { Metadata } from "next";
import Providers from '@/providers'
import "../styles/globals.css";
import localFont from 'next/font/local'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from '@/components/layout/home/Header'
/* import HeaderOld from '@/components/layout/home/HeaderOld' */
import Footer from '@/components/layout/home/Footer'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Geist } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "sabka",
  description: "Generated by create next app",
};

const iranYekan = localFont({
  src: [
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-UltraLight.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-DemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-ExtraBold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/iranyekan/woff2/IRANYekanX-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-iranYekan',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${iranYekan.variable}  ${geistSans.variable}  antialiased`}
      >
        <Providers>
          <Header />
          <main className="pt-[84px]">

            {children}
            <Footer />
          </main>

        </Providers>
      </body>
    </html>
  );
}
