import type { Metadata } from "next";
import Providers from '@/providers'
import "../styles/globals.css";
import localFont from 'next/font/local'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";





export const metadata: Metadata = {
  title: "sabka",
  description: "Generated by create next app",
};
const damoon = localFont({
  src: [
    {
      path: '../../public/assets/fonts/damoon/DAMOONFANUM-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/damoon/DAMOONFANUM-ExtraLight.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/damoon/DAMOONFANUM-Light.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/damoon/DAMOONFANUM-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/damoon/DAMOONFANUM-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/damoon/DAMOONFANUM-ExtraBold.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-damoon',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${damoon.variable}  antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
